-- Запустите этот файл один раз в Supabase:
-- Dashboard → SQL Editor → New query → Run.

create schema if not exists extensions;
create extension if not exists pgcrypto with schema extensions;

create schema if not exists private;
revoke all on schema private from public, anon, authenticated;

create table if not exists private.site_secrets (
    secret_name text primary key,
    secret_hash text not null,
    updated_at timestamptz not null default now()
);

alter table private.site_secrets enable row level security;
revoke all on private.site_secrets from public, anon, authenticated;

create or replace function public.verify_site_password(
    candidate_password text
)
returns boolean
language sql
security definer
set search_path = ''
as $$
    select exists (
        select 1
        from private.site_secrets
        where secret_name = 'entry_password'
          and secret_hash = extensions.crypt(
              candidate_password,
              secret_hash
          )
    );
$$;

revoke all on function public.verify_site_password(text) from public;
grant execute on function public.verify_site_password(text)
    to anon, authenticated;

create or replace function private.normalize_verification_answer(
    answer text
)
returns text
language sql
immutable
set search_path = ''
as $$
    select lower(
        regexp_replace(
            trim(replace(coalesce(answer, ''), 'ё', 'е')),
            '\s+',
            ' ',
            'g'
        )
    );
$$;

create table if not exists private.verification_questions (
    id bigint generated by default as identity primary key,
    question_text text not null unique,
    answer_hash text not null,
    is_final boolean not null default false,
    is_active boolean not null default true,
    created_at timestamptz not null default now()
);

alter table private.verification_questions enable row level security;
revoke all on private.verification_questions
    from public, anon, authenticated;

create unique index if not exists one_active_final_verification_question
    on private.verification_questions (is_final)
    where is_final and is_active;

create or replace function public.get_verification_question(
    excluded_question_ids bigint[] default '{}'::bigint[]
)
returns table(question_id bigint, question_text text)
language sql
security definer
set search_path = ''
as $$
    select id, verification_questions.question_text
    from private.verification_questions
    where is_active
      and not is_final
      and not (id = any(coalesce(excluded_question_ids, '{}'::bigint[])))
    order by random()
    limit 1;
$$;

create or replace function public.get_final_verification_question()
returns table(question_id bigint, question_text text)
language sql
security definer
set search_path = ''
as $$
    select id, verification_questions.question_text
    from private.verification_questions
    where is_active and is_final
    limit 1;
$$;

create or replace function public.verify_verification_answer(
    question_id bigint,
    candidate_answer text
)
returns boolean
language sql
security definer
set search_path = ''
as $$
    select exists (
        select 1
        from private.verification_questions
        where id = question_id
          and is_active
          and answer_hash = extensions.crypt(
              private.normalize_verification_answer(candidate_answer),
              answer_hash
          )
    );
$$;

revoke all on function public.get_verification_question(bigint[])
    from public;
revoke all on function public.get_final_verification_question()
    from public;
revoke all on function public.verify_verification_answer(bigint, text)
    from public;
grant execute on function public.get_verification_question(bigint[])
    to anon, authenticated;
grant execute on function public.get_final_verification_question()
    to anon, authenticated;
grant execute on function public.verify_verification_answer(bigint, text)
    to anon, authenticated;

create table if not exists public.visited_places (
    event_id text primary key,
    visited_at timestamptz not null default now(),
    author_impression text not null default '',
    denis_impression text not null default '',
    updated_at timestamptz not null default now()
);

create table if not exists public.visited_media (
    id uuid primary key default gen_random_uuid(),
    event_id text not null references public.visited_places(event_id)
        on delete cascade,
    storage_path text not null unique,
    media_type text not null,
    original_name text not null,
    created_at timestamptz not null default now()
);

alter table public.visited_places enable row level security;
alter table public.visited_media enable row level security;

grant select, insert, update, delete
    on public.visited_places to authenticated;
grant select, insert, update, delete
    on public.visited_media to authenticated;

drop policy if exists "Shared account can read visited places"
    on public.visited_places;
create policy "Shared account can read visited places"
    on public.visited_places for select
    to authenticated
    using (true);

drop policy if exists "Shared account can add visited places"
    on public.visited_places;
create policy "Shared account can add visited places"
    on public.visited_places for insert
    to authenticated
    with check (true);

drop policy if exists "Shared account can update visited places"
    on public.visited_places;
create policy "Shared account can update visited places"
    on public.visited_places for update
    to authenticated
    using (true)
    with check (true);

drop policy if exists "Shared account can delete visited places"
    on public.visited_places;
create policy "Shared account can delete visited places"
    on public.visited_places for delete
    to authenticated
    using (true);

drop policy if exists "Shared account can read visited media"
    on public.visited_media;
create policy "Shared account can read visited media"
    on public.visited_media for select
    to authenticated
    using (true);

drop policy if exists "Shared account can add visited media"
    on public.visited_media;
create policy "Shared account can add visited media"
    on public.visited_media for insert
    to authenticated
    with check (true);

drop policy if exists "Shared account can delete visited media"
    on public.visited_media;
create policy "Shared account can delete visited media"
    on public.visited_media for delete
    to authenticated
    using (true);

insert into storage.buckets (
    id,
    name,
    public,
    file_size_limit,
    allowed_mime_types
)
values (
    'visited-media',
    'visited-media',
    false,
    52428800,
    array[
        'image/jpeg',
        'image/png',
        'image/webp',
        'image/gif',
        'video/mp4',
        'video/quicktime',
        'video/webm'
    ]
)
on conflict (id) do update set
    public = excluded.public,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Shared account can view archive files"
    on storage.objects;
create policy "Shared account can view archive files"
    on storage.objects for select
    to authenticated
    using (bucket_id = 'visited-media');

drop policy if exists "Shared account can upload archive files"
    on storage.objects;
create policy "Shared account can upload archive files"
    on storage.objects for insert
    to authenticated
    with check (bucket_id = 'visited-media');

drop policy if exists "Shared account can delete archive files"
    on storage.objects;
create policy "Shared account can delete archive files"
    on storage.objects for delete
    to authenticated
    using (bucket_id = 'visited-media');
